print ('hello world')
print ('-----Voravit Liammongkhonkul-----')
print ('-----Your Score-----')
print (FE,'-----',89.50,'คะแนน')
print (GB,'-----',77.50,'คะแนน')
print (ICS,'-----',64.50,'คะแนน')
print (CP,'-----',69,'คะแนน')
